FROM python:3.11

WORKDIR /app

COPY pipeline/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY pipeline/ ./pipeline
COPY ad_hoc/ ./ad_hoc

WORKDIR /app/pipeline

CMD ["tail", "-f", "/dev/null"]