CASE_LINK_RADIUS_KM = 0.5
MASS_OUTAGE_CONFIRMATION_COUNT = 3

CASE_TYPE_NORMAL = "normal"
CASE_TYPE_FAST_TRACK = "fast_track"
CASE_TYPE_MASS_OUTAGE = "mass_outage"

STATUS_REPORTED = "reported"
STATUS_INVESTIGATING = "investigating"
STATUS_REPAIRING = "repairing"
STATUS_RESTORED = "restored"
STATUS_MERGED = "merged"

INACTIVE_CASE_STATUSES = (STATUS_RESTORED, STATUS_MERGED)
