# Generated by Django 5.2.15 on 2026-06-23 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutageCase',
            fields=[
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='ไฟดับบริเวณใกล้เคียง', max_length=255)),
                ('status', models.CharField(choices=[('reported', 'ได้รับแจ้งเหตุ'), ('investigating', 'กำลังตรวจสอบพิกัด'), ('repairing', 'กำลังดำเนินการซ่อมแซม'), ('restored', 'จ่ายไฟคืนกระแสสำเร็จ')], default='reported', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('oms_etr', models.DateTimeField(blank=True, help_text='เวลาซ่อมเสร็จจาก OMS', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='รหัสผู้ใช้งานจากหน้าเว็บ', max_length=255, null=True)),
                ('ca_number', models.CharField(help_text='หมายเลขผู้ใช้ไฟ (หลาย Session สามารถแจ้ง CA เดียวกันได้)', max_length=12)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('chat_history', models.TextField(default='[]', help_text='เก็บประวัติสนทนาล่าสุดของ Session นี้')),
                ('needs_eta', models.BooleanField(default=False, help_text='ต้องการทราบเวลาช่างมาถึง')),
                ('needs_etr', models.BooleanField(default=False, help_text='ต้องการทราบเวลาไฟมา')),
                ('is_resolved', models.BooleanField(default=False, help_text='จบการสนทนาหรือไฟมาปกติแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_customers', to='oms.outagecase')),
            ],
        ),
    ]
