# Generated by Django 5.2.15 on 2026-06-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outagecase',
            name='status',
            field=models.CharField(choices=[('reported', 'ได้รับแจ้งเหตุ'), ('investigating', 'กำลังดำเนินการตรวจสอบ'), ('repairing', 'กำลังดำเนินการซ่อมแซม'), ('restored', 'จ่ายไฟคืนกระแสสำเร็จ')], default='reported', max_length=20),
        ),
    ]
