# Generated by Django 5.2.15 on 2026-06-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_alter_outagecase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagecase',
            name='eta_target_time',
            field=models.DateTimeField(blank=True, help_text='เวลาเป้าหมายที่ช่างจะไปถึงหน้างาน (ETA)', null=True),
        ),
    ]
