# Generated by Django 5.2.15 on 2026-06-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0003_outagecase_eta_target_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreport',
            name='fast_track_quota',
            field=models.IntegerField(default=1, help_text='โควต้าการแจ้งไฟดับซ้ำซ้อน (1 ครั้ง/เคส)'),
        ),
        migrations.AddField(
            model_name='outagecase',
            name='celery_eta_task_id',
            field=models.CharField(blank=True, help_text='ID ของ Celery Task สำหรับนับเวลา ETA', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outagecase',
            name='celery_etr_task_id',
            field=models.CharField(blank=True, help_text='ID ของ Celery Task สำหรับนับเวลา ETR', max_length=255, null=True),
        ),
    ]
