# Generated by Django 5.2.15 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oms", "0004_customerreport_fast_track_quota_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerreport",
            name="pdpa_consent",
            field=models.BooleanField(
                default=False,
                help_text="ลูกค้าให้ความยินยอมให้ตรวจสอบข้อมูลด้วยหมายเลข CA",
            ),
        ),
        migrations.AddField(
            model_name="customerreport",
            name="pdpa_consent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="เวลาที่ลูกค้าให้ PDPA consent",
                null=True,
            ),
        ),
    ]
