# Generated by Django 5.2.15 on 2026-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0005_customerreport_pdpa_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('ca_number', models.CharField(db_index=True, max_length=12, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('pea_area', models.CharField(blank=True, max_length=255)),
                ('user_type', models.CharField(blank=True, max_length=255)),
                ('outage_freq_yearly', models.CharField(blank=True, max_length=100)),
                ('report_channel', models.CharField(blank=True, max_length=255)),
                ('is_ready', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('eta_result', models.FloatField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ca_number'],
            },
        ),
    ]
