# Generated by Django 5.2.15 on 2026-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0006_customerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagecase',
            name='assessment_eta_formatted',
            field=models.CharField(blank=True, help_text='ETA label จาก pea-estimated.services', max_length=50),
        ),
        migrations.AddField(
            model_name='outagecase',
            name='assessment_eta_minutes',
            field=models.FloatField(blank=True, help_text='ETA เป็นนาทีจาก pea-estimated.services', null=True),
        ),
        migrations.AddField(
            model_name='outagecase',
            name='assessment_fastest_branch',
            field=models.CharField(blank=True, help_text='สาขาที่ประเมินว่าไปถึงเร็วที่สุด', max_length=255),
        ),
        migrations.AddField(
            model_name='outagecase',
            name='assessment_payload',
            field=models.JSONField(blank=True, default=dict, help_text='ผลลัพธ์ล่าสุดจาก pea-estimated.services'),
        ),
        migrations.AddField(
            model_name='outagecase',
            name='pluem_etr_minutes',
            field=models.FloatField(blank=True, help_text='ETR เป็นนาทีจากโมเดลพี่ปลื้ม', null=True),
        ),
        migrations.AddField(
            model_name='outagecase',
            name='pluem_etr_target_time',
            field=models.DateTimeField(blank=True, help_text='เวลาไฟกลับโดยประมาณจากโมเดลพี่ปลื้ม', null=True),
        ),
    ]
