# Generated by Django 5.2.15 on 2026-06-26 05:40

import django.db.models.deletion
import django.utils.timezone
import json
from django.db import migrations, models


def normalize_chat_history(apps, schema_editor):
    CustomerReport = apps.get_model("oms", "CustomerReport")
    for report in CustomerReport.objects.all():
        value = report.chat_history
        try:
            parsed = json.loads(value or "[]") if isinstance(value, str) else value
        except (TypeError, ValueError):
            parsed = []

        if not isinstance(parsed, list):
            parsed = []

        report.chat_history = json.dumps(parsed, ensure_ascii=False)
        report.save(update_fields=["chat_history"])


def backfill_outage_case_snapshots(apps, schema_editor):
    OutageCase = apps.get_model("oms", "OutageCase")
    CustomerReport = apps.get_model("oms", "CustomerReport")

    for index, case in enumerate(
        OutageCase.objects.order_by("created_at", "case_id"), start=1
    ):
        ca_numbers = (
            CustomerReport.objects.filter(related_case=case)
            .exclude(ca_number__isnull=True)
            .exclude(ca_number="")
            .values_list("ca_number", flat=True)
            .distinct()
        )
        case.lv_group_id = index
        case.affected_ca_numbers = sorted(ca_numbers)
        case.save(update_fields=["lv_group_id", "affected_ca_numbers"])


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0007_outagecase_assessment_eta_formatted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagecase',
            name='affected_ca_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot รายการ CA ที่ผูกกับเคสนี้'),
        ),
        migrations.AddField(
            model_name='outagecase',
            name='lv_group_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='เลขกลุ่มเคสแบบรัน 1-n สำหรับ filter/readability', null=True, unique=True),
        ),
        migrations.RunPython(normalize_chat_history, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customerreport',
            name='chat_history',
            field=models.JSONField(blank=True, default=list, help_text='เก็บประวัติสนทนาแบบ dialog'),
        ),
        migrations.RunPython(backfill_outage_case_snapshots, migrations.RunPython.noop),
        migrations.CreateModel(
            name='OutageRestorationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lv_group_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('affected_ca_numbers', models.JSONField(blank=True, default=list)),
                ('restored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('eta_target_time_at_restore', models.DateTimeField(blank=True, null=True)),
                ('oms_etr_at_restore', models.DateTimeField(blank=True, null=True)),
                ('pluem_etr_target_time_at_restore', models.DateTimeField(blank=True, null=True)),
                ('effective_etr_at_restore', models.DateTimeField(blank=True, null=True)),
                ('etr_source', models.CharField(blank=True, max_length=50)),
                ('etr_delta_minutes', models.FloatField(blank=True, null=True)),
                ('case_status_at_restore', models.CharField(default='restored', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_log', to='oms.outagecase')),
            ],
            options={
                'ordering': ['-restored_at'],
            },
        ),
    ]
