# Generated by Codex on 2026-06-30

from datetime import timedelta
from django.db import migrations, models


def backfill_sla_and_case_type(apps, schema_editor):
    OutageCase = apps.get_model("oms", "OutageCase")

    for case in OutageCase.objects.all():
        reference_time = case.updated_at if case.oms_etr else case.created_at
        reason = "oms_etr_update" if case.oms_etr else "case_created"
        case_type = (
            "fast_track"
            if str(case.title or "").startswith("[ด่วน! ไฟดับซ้ำซ้อน]")
            else "normal"
        )

        if reference_time:
            case.sla_reference_time = reference_time
            case.sla_target_time = reference_time + timedelta(hours=4)
            case.sla_reason = reason
        case.case_type = case_type
        case.save(
            update_fields=[
                "case_type",
                "sla_reference_time",
                "sla_target_time",
                "sla_reason",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("oms", "0008_outagecase_affected_ca_numbers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outagecase",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("normal", "เคสปกติ"),
                    ("fast_track", "เคสเร่งด่วน"),
                ],
                db_index=True,
                default="normal",
                help_text="ประเภทเคส เช่น normal หรือ fast_track",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="outagecase",
            name="oms_etr_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="เวลาที่ OMS อัปเดต ETR ล่าสุด", null=True
            ),
        ),
        migrations.AddField(
            model_name="outagecase",
            name="sla_reference_time",
            field=models.DateTimeField(
                blank=True, help_text="เวลาอ้างอิงสำหรับ SLA 4 ชั่วโมง", null=True
            ),
        ),
        migrations.AddField(
            model_name="outagecase",
            name="sla_target_time",
            field=models.DateTimeField(
                blank=True, help_text="เวลาเป้าหมาย SLA 4 ชั่วโมง", null=True
            ),
        ),
        migrations.AddField(
            model_name="outagecase",
            name="sla_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="เหตุผลที่ตั้ง SLA ล่าสุด",
                max_length=50,
            ),
        ),
        migrations.RunPython(backfill_sla_and_case_type, migrations.RunPython.noop),
    ]
