# Generated by Codex on 2026-06-30

from datetime import timedelta
from django.db import migrations


def normalize_sla_to_case_start(apps, schema_editor):
    OutageCase = apps.get_model("oms", "OutageCase")

    for case in OutageCase.objects.exclude(created_at__isnull=True):
        case_start_times = [
            value for value in [case.sla_reference_time, case.created_at] if value
        ]
        sla_reference_time = min(case_start_times)
        sla_target_time = sla_reference_time + timedelta(hours=4)
        sla_reason = case.sla_reason or (
            "fast_track" if case.case_type == "fast_track" else "case_created"
        )

        OutageCase.objects.filter(pk=case.pk).update(
            sla_reference_time=sla_reference_time,
            sla_target_time=sla_target_time,
            sla_reason=sla_reason,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("oms", "0009_outagecase_sla_and_case_type"),
    ]

    operations = [
        migrations.RunPython(normalize_sla_to_case_start, migrations.RunPython.noop),
    ]
