# Generated by Django 5.2.16 on 2026-07-11 00:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models
from django.utils.dateparse import parse_datetime


def backfill_chat_messages(apps, schema_editor):
    CustomerReport = apps.get_model("oms", "CustomerReport")
    OutageCase = apps.get_model("oms", "OutageCase")
    ChatMessage = apps.get_model("oms", "ChatMessage")

    session_ids = (
        CustomerReport.objects.exclude(session_id__isnull=True)
        .exclude(session_id="")
        .values_list("session_id", flat=True)
        .distinct()
    )
    for session_id in session_ids.iterator():
        reports = list(
            CustomerReport.objects.filter(session_id=session_id)
            .order_by("-updated_at", "-id")
        )
        report = next((item for item in reports if item.chat_history), None)
        if not report or not isinstance(report.chat_history, list):
            continue

        created_messages = []
        for item in report.chat_history or []:
            if not isinstance(item, dict):
                continue
            content = item.get("message") or item.get("content") or ""
            if not content:
                continue
            raw_role = str(item.get("role") or "").lower()
            event_type = str(item.get("event_type") or "")
            if event_type:
                role = "system"
            elif "user" in raw_role:
                role = "user"
            else:
                role = "agent"

            created_at = parse_datetime(str(item.get("timestamp") or ""))
            if created_at and django.utils.timezone.is_naive(created_at):
                created_at = django.utils.timezone.make_aware(created_at)
            created_at = created_at or report.updated_at or django.utils.timezone.now()

            case_id = item.get("case_id") or report.related_case_id
            if case_id:
                try:
                    case_id = uuid.UUID(str(case_id))
                except (TypeError, ValueError, AttributeError):
                    case_id = None
            if case_id and not OutageCase.objects.filter(pk=case_id).exists():
                case_id = None
            notification_key = item.get("notification_key") or None
            if event_type and not notification_key:
                notification_key = "|".join(
                    str(value or "")
                    for value in (
                        event_type,
                        item.get("ca_number") or report.ca_number,
                        report.id,
                        case_id,
                        content,
                    )
                )
            if notification_key and ChatMessage.objects.filter(
                notification_key=notification_key
            ).exists():
                continue

            message = ChatMessage.objects.create(
                session_id=session_id,
                report_id=report.id,
                case_id=case_id,
                role=role,
                content=str(content),
                ca_number=str(item.get("ca_number") or report.ca_number or ""),
                event_type=event_type,
                notification_key=notification_key,
                closed_loop_kind=str(item.get("closed_loop_kind") or ""),
                acknowledged_at=(created_at if event_type else None),
                created_at=created_at,
            )
            created_messages.append(message)

        if created_messages and created_messages[-1].event_type:
            ChatMessage.objects.filter(pk=created_messages[-1].pk).update(
                acknowledged_at=None
            )


def reverse_backfill(apps, schema_editor):
    ChatMessage = apps.get_model("oms", "ChatMessage")
    ChatMessage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0017_unique_active_report_per_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System notification')], max_length=20)),
                ('content', models.TextField()),
                ('ca_number', models.CharField(blank=True, default='', max_length=12)),
                ('event_type', models.CharField(blank=True, default='', max_length=50)),
                ('notification_key', models.TextField(blank=True, null=True, unique=True)),
                ('closed_loop_kind', models.CharField(blank=True, default='', max_length=50)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='oms.outagecase')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='oms.customerreport')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('ca_number', models.CharField(max_length=12)),
                ('pdpa_consent', models.BooleanField(default=False)),
                ('response_state', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('celery_task_id', models.CharField(max_length=255, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_agent_job', to='oms.chatmessage')),
                ('user_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agent_job', to='oms.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session_id', 'created_at', 'id'], name='oms_chatmes_session_341db5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session_id', 'acknowledged_at'], name='oms_chatmes_session_5edfc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('session_id',), name='unique_active_agent_job_per_session'),
        ),
        migrations.RunPython(backfill_chat_messages, reverse_backfill),
    ]
