# Generated by Django 5.2.16 on 2026-07-17 06:53

import django.contrib.postgres.indexes
import django.db.models.expressions
from django.db import migrations, models


CREATE_LV_GROUP_SEQUENCE = """
CREATE SEQUENCE IF NOT EXISTS oms_outagecase_lv_group_id_seq AS integer;
SELECT setval(
    'oms_outagecase_lv_group_id_seq',
    GREATEST(COALESCE(MAX(lv_group_id), 0) + 1, 1),
    false
)
FROM oms_outagecase;
ALTER SEQUENCE oms_outagecase_lv_group_id_seq
    OWNED BY oms_outagecase.lv_group_id;
"""

DROP_LV_GROUP_SEQUENCE = "DROP SEQUENCE IF EXISTS oms_outagecase_lv_group_id_seq;"


class Migration(migrations.Migration):

    dependencies = [
        ("oms", "0018_chatmessage_agentjob_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_LV_GROUP_SEQUENCE,
            reverse_sql=DROP_LV_GROUP_SEQUENCE,
        ),
        migrations.RemoveField(
            model_name="customerreport",
            name="chat_history",
        ),
        migrations.AlterField(
            model_name="customerlocation",
            name="ca_number",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="outagecase",
            name="lv_group_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_default=django.db.models.expressions.RawSQL(
                    "nextval('oms_outagecase_lv_group_id_seq')", []
                ),
                help_text="เลขกลุ่มเคสแบบรัน 1-n สำหรับ filter/readability",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="agentjob",
            index=models.Index(
                condition=models.Q(
                    ("status", "succeeded"),
                    ("response_message__isnull", False),
                ),
                fields=["session_id", "ca_number", "-response_message"],
                name="oms_job_state_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentjob",
            index=models.Index(
                fields=["status", "-created_at"],
                name="oms_job_status_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session_id", "ca_number", "created_at", "id"],
                name="oms_msg_session_ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                condition=models.Q(
                    ("role", "system"),
                    ("acknowledged_at__isnull", True),
                    ("notification_key__isnull", False),
                ),
                fields=["session_id", "created_at", "id"],
                name="oms_msg_pending_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerreport",
            index=models.Index(
                fields=["session_id", "is_resolved", "-updated_at", "-id"],
                name="oms_report_session_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerreport",
            index=models.Index(
                fields=["ca_number", "is_resolved", "-updated_at"],
                name="oms_report_ca_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerreport",
            index=models.Index(
                fields=["related_case", "is_resolved"],
                name="oms_report_case_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outagecase",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["affected_ca_numbers"],
                name="oms_case_ca_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="outagecase",
            index=models.Index(
                fields=["status", "-updated_at"],
                name="oms_case_status_upd_idx",
            ),
        ),
    ]
